# Generated by Django 2.1 on 2019-04-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='visitor', max_length=64),
        ),
    ]
